# Generated by Django 5.2.6 on 2025-10-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0010_alter_restaurant_price_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
